# Generated by Django 5.2.8 on 2025-11-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_project_team_head_projectdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_document',
            new_name='document_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='voice_note',
        ),
        migrations.AddField(
            model_name='project',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to='project_documents/'),
        ),
        migrations.AddField(
            model_name='project',
            name='document_3',
            field=models.FileField(blank=True, null=True, upload_to='project_documents/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_logo',
            field=models.ImageField(blank=True, null=True, upload_to='project_logos/'),
        ),
    ]
