# Generated by Django 5.2.8 on 2025-11-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_rename_project_document_project_document_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDocument',
        ),
    ]
