# Generated by Django 5.2.8 on 2025-11-12 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0008_remove_project_team_head_project_head_backend_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('PARTIALLY_DONE', 'Partially Done'), ('COMPLETE', 'Complete')], default='INCOMPLETE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_updates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_updates', to='pms.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
