# Generated by Django 5.2.8 on 2025-11-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0009_workupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectupdate',
            name='sub_stage',
        ),
        migrations.RemoveField(
            model_name='projectupdate',
            name='update_intent',
        ),
    ]
