# Generated by Django 5.2.8 on 2025-11-14 05:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0013_dailyupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='document_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='document_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='document_3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='head_backend',
        ),
        migrations.RemoveField(
            model_name='project',
            name='head_frontend',
        ),
        migrations.RemoveField(
            model_name='project',
            name='head_uiux',
        ),
        migrations.AddField(
            model_name='project',
            name='team_head',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'EMPLOYEE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyupdate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='project_documents/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pms.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
