# Generated by Django 5.2.8 on 2025-11-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_remove_project_document_1_remove_project_document_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status_update',
            field=models.CharField(blank=True, choices=[('INCOMPLETE', 'Incomplete'), ('PARTIALLY_DONE', 'Partially Done'), ('COMPLETE', 'Complete')], default='INCOMPLETE', max_length=20),
        ),
    ]
