# Generated by Django 5.2.8 on 2025-11-14 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0015_project_project_status_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskupdate',
            name='task',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskupdate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='developer_status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tester_status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ui_ux_status',
        ),
        migrations.CreateModel(
            name='TaskPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_pages', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_pages', to='pms.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskUpdate',
        ),
    ]
