# Generated by Django 5.2.8 on 2025-11-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0016_remove_taskupdate_task_remove_comment_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskpage',
            options={'ordering': ['created_at']},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
