# Generated by Django 5.2.8 on 2025-11-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0017_alter_taskpage_options_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpage',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
