# Generated by Django 5.2.8 on 2025-11-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0018_taskpage_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectupdate',
            name='update_status',
            field=models.CharField(blank=True, choices=[('INITIATE', 'Initiate'), ('ONGOING', 'Ongoing'), ('ONHOLD', 'On-Hold'), ('COMPLETE', 'Complete')], max_length=20, null=True),
        ),
    ]
