# Generated by Django 5.2.8 on 2025-11-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0019_alter_projectupdate_update_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectupdate',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_chat_files/'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='sub_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='update_intent',
            field=models.CharField(blank=True, choices=[('INFO', 'Info'), ('QUERY', 'Query'), ('ISSUE', 'Issue'), ('APPROVAL', 'Approval')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_chat_images/'),
        ),
    ]
