# Generated by Django 5.2.8 on 2025-11-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0020_alter_projectupdate_options_projectupdate_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectupdate',
            name='sub_stage',
        ),
        migrations.RemoveField(
            model_name='projectupdate',
            name='update_intent',
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='subject',
            field=models.CharField(blank=True, choices=[('INFO', 'Info'), ('QUERY', 'Query'), ('ISSUE', 'Issue'), ('APPROVAL', 'Approval')], default='INFO', max_length=10, null=True),
        ),
    ]
