# Generated by Django 5.2.8 on 2025-11-18 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0021_remove_projectupdate_sub_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProjectUpdateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_updates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pms.projectupdate')),
            ],
        ),
    ]
