# Generated by Django 5.2.8 on 2025-11-18 09:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0022_projectupdate_title_projectupdateattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='dailyupdate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyupdate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyUpdateLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.TimeField(help_text='HH:MM')),
                ('daily_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='pms.dailyupdate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.project')),
                ('task_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.taskpage')),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyupdate',
            name='remarks',
        ),
    ]
