# Generated by Django 5.2.8 on 2025-11-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0023_alter_dailyupdate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyupdatelineitem',
            name='time_spent',
            field=models.CharField(help_text='e.g. 2:30 or 2 hrs', max_length=50),
        ),
    ]
