# Generated by Django 5.2.8 on 2025-11-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0024_alter_dailyupdatelineitem_time_spent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='subject',
            field=models.CharField(blank=True, choices=[('INFO', 'Info'), ('QUERY', 'Query'), ('ISSUE', 'Issue'), ('APPROVAL', 'Approval')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
