# Generated by Django 5.2.8 on 2025-11-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0025_alter_projectupdate_options_projectupdate_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='category',
            field=models.CharField(choices=[('UPDATE', 'Update/Report'), ('RECOMMENDATION', 'Recommendation')], default='UPDATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20, null=True),
        ),
    ]
