# Generated by Django 5.2.8 on 2025-11-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0026_projectupdate_category_alter_projectupdate_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='google_meet_link',
            field=models.URLField(blank=True, help_text='e.g., https://meet.google.com/abc-xyz-123', null=True),
        ),
    ]
